# Generated by Django 4.0.4 on 2022-05-15 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckThema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='デッキテーマ名')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='スキル名')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='大会名')),
                ('start', models.DateTimeField(verbose_name='開始日時')),
                ('finish', models.DateTimeField(verbose_name='終了日時')),
                ('participants', models.ManyToManyField(related_name='tournament', to=settings.AUTH_USER_MODEL, verbose_name='参加者')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerToNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='player番号')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.tournament', verbose_name='大会名')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.DateTimeField(default=django.utils.timezone.now, verbose_name='試合終了時刻')),
                ('first_second', models.BooleanField(verbose_name='先行or後攻')),
                ('result', models.IntegerField(choices=[(1, '勝ち'), (-1, '負け'), (0, '引き分け')], verbose_name='勝敗')),
                ('deck_thema1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game1', to='game.deckthema', verbose_name='使用テーマ')),
                ('deck_thema2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game2', to='game.deckthema', verbose_name='相手テーマ')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game1', to=settings.AUTH_USER_MODEL, verbose_name='player1')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game', to=settings.AUTH_USER_MODEL, verbose_name='player2')),
                ('skill1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game1', to='game.skill', verbose_name='使用スキル')),
                ('skill2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game2', to='game.skill', verbose_name='相手スキル')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game', to='game.tournament', verbose_name='大会名')),
            ],
        ),
        migrations.AddConstraint(
            model_name='playertonum',
            constraint=models.UniqueConstraint(fields=('tournament', 'num'), name='num_unique_for_tournament'),
        ),
    ]
