# Generated by Django 4.0.4 on 2022-05-15 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='tournament', to=settings.AUTH_USER_MODEL, verbose_name='参加者'),
        ),
    ]
