# Generated by Django 4.0.4 on 2022-05-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='first_second',
            field=models.BooleanField(choices=[(True, '先行'), (False, '後攻')], verbose_name='先行or後攻'),
        ),
    ]
