# Generated by Django 4.0.4 on 2022-05-17 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_first_second'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='finished',
        ),
        migrations.AddField(
            model_name='game',
            name='finished_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='試合日付'),
        ),
        migrations.AddField(
            model_name='game',
            name='finished_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='終了時間'),
        ),
    ]
