# Generated by Django 4.0.4 on 2022-05-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_game_finished_game_finished_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thema',
            field=models.CharField(blank=True, max_length=100, verbose_name='テーマ相性用'),
        ),
    ]
