# Generated by Django 4.0.4 on 2022-05-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_thema'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckthema',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='themas/', verbose_name='テーマサムネイル'),
        ),
    ]
