# Generated by Django 4.0.4 on 2022-05-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_deckthema_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='is_valid'),
        ),
    ]
