# Generated by Django 4.0.4 on 2022-05-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='count',
            field=models.BooleanField(default=False, verbose_name='集計用'),
        ),
    ]
