# Generated by Django 4.0.4 on 2022-05-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_game_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='count',
            new_name='used',
        ),
    ]
